# Generated by Django 4.1.7 on 2023-03-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('recipes', '0001_initial'), ('recipes', '0002_rename_allergen_group_ingredient_allergy_group'), ('recipes', '0003_amount_delete_recipequantity_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('allergy_group', models.IntegerField(blank=True, choices=[(None, ''), (1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], null=True, verbose_name='аллергическая группа')),
                ('calories', models.IntegerField(verbose_name='Ккал на 100 г')),
                ('liquid', models.BooleanField(default=False, verbose_name='жидкий')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('type', models.IntegerField(choices=[(1, 'завтрак'), (2, 'обед/ужин'), (3, 'десерт')], verbose_name='тип')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(verbose_name='количество, г/мл')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeQuantity', to='recipes.ingredient', verbose_name='ингредиенты'),
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(verbose_name='количество, г/мл')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.recipe', verbose_name='рецепт')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeQuantity',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Amount', to='recipes.ingredient', verbose_name='ингредиенты'),
        ),
    ]
