# Generated by Django 4.1.7 on 2023-03-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(verbose_name='количество, г/мл')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('allergy_group', models.IntegerField(blank=True, choices=[(None, ''), (1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], null=True, verbose_name='аллергическая группа')),
                ('calories', models.IntegerField(verbose_name='Ккал на 100 г')),
                ('liquid', models.BooleanField(default=False, verbose_name='жидкий')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('type', models.IntegerField(choices=[(1, 'завтрак'), (2, 'обед/ужин'), (3, 'десерт')], verbose_name='тип')),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='recipes.Amount', to='recipes.ingredient', verbose_name='ингредиенты')),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AddField(
            model_name='amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
