# Generated by Django 4.1.7 on 2023-03-17 15:48

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_dailymenu_weekdaymenu_weeklymenu_weekdaymenu_week'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='dailymenu',
            name='meals',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='weekdaymenu',
            name='day_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_day_menus', to='recipes.dailymenu', verbose_name='дневное меню'),
        ),
    ]
