# Generated by Django 4.1.7 on 2023-03-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_weeklymenu_user_weeklymenu_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(None, ''), (1, 'Рыба и морепродукты'), (2, 'Мясо'), (3, 'Зерновые'), (4, 'Продукты пчеловодства'), (5, 'Орехи и бобовые'), (6, 'Молочные продукты')], verbose_name='аллергическая группа')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, 'завтрак'), (2, 'обед/ужин'), (3, 'десерт')], verbose_name='категория')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergy_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.allergy', verbose_name='аллергическая группа'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.mealtype', verbose_name='категория'),
        ),
    ]
