# Generated by Django 4.1.7 on 2023-03-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_allergy_mealtype_ingredient_allergy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.allergy', verbose_name='аллергическая группа'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.mealtype', verbose_name='категория'),
        ),
    ]
