# Generated by Django 4.1.7 on 2023-03-18 12:59

from django.db import migrations


def forwards(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Ingredient = apps.get_model('recipes', 'Ingredient')

    for recipe in Recipe.objects.all():
        recipe.category_id = recipe.type
        recipe.save()

    for ingredient in Ingredient.objects.all():
        ingredient.allergy_type_id = ingredient.allergy_group
        ingredient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredient_allergy_type_alter_recipe_category'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
