# Generated by Django 4.1.7 on 2023-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_ingredient_allergy_group_remove_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='label',
            field=models.CharField(default='заменить', max_length=20, verbose_name='название'),
            preserve_default=False,
        ),
    ]
