# Generated by Django 4.1.7 on 2023-03-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_subscription_user'),
        ('recipes', '0012_mealtype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenu',
            name='subscription_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menus', to='members.subscription', verbose_name='подписка'),
            preserve_default=False,
        ),
    ]
