# Generated by Django 4.1.7 on 2023-03-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_weeklymenu_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymenu',
            old_name='subscription_new',
            new_name='subscription',
        ),
    ]
