# Generated by Django 4.1.7 on 2023-03-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_ingredient_allergy_group_remove_recipe_type'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.ManyToManyField(to='recipes.allergy', verbose_name='аллергии')),
                ('meals', models.ManyToManyField(to='recipes.mealtype', verbose_name='типы блюд')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='подписка')),
            ],
        ),
    ]
