# Generated by Django 4.1.7 on 2023-03-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_menucategory_recipe_menu_category'),
        ('members', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='срок подписки (месяцев)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.menucategory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='person_count',
            field=models.PositiveIntegerField(default=1, verbose_name='количество персон'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='recipes.allergy', verbose_name='аллергии'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='meals',
            field=models.ManyToManyField(blank=True, to='recipes.mealtype', verbose_name='типы блюд'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
